import{a as v,S as q,i as s}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",E="54692285-0e8498ada734ef5e15a7b52ba";async function h(r,t=1){return await v($,{params:{key:E,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(i=>i.data)}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".button-load"),x=new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function M(r){return r.map(({webformatURL:t,largeImageURL:i,tags:c,likes:e,views:o,comments:n,downloads:S})=>`<li class="list-item">
            <a href="${i}">
                <img src="${t}" alt="${c}"  width="360"/>
            </a>

            <div class="wrapper">
                <h3 class="wrapper-text">Likers <span class="wrapper-span">${e}</span></h3>
                <h3 class="wrapper-text">Views <span class="wrapper-span">${o}</span></h3>
                <h3 class="wrapper-text">Comments <span class="wrapper-span">${n}</span></h3>
                <h3 class="wrapper-text">Downloads <span class="wrapper-span">${S}</span></h3>
            </div>
        </li>`).join("")}function g(r){f.insertAdjacentHTML("beforeend",M(r)),x.refresh()}function P(){f.innerHTML=""}function L(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}function b(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const R=document.querySelector(".form"),B=document.querySelector(".input"),O=document.querySelector(".button-load");R.addEventListener("submit",C);O.addEventListener("click",H);let l,p,u,a;async function C(r){if(r.preventDefault(),a=1,d(),l=B.value.trim(),!l){s.error({title:"Error",message:"Sorry, you send empty filed",position:"topRight"});return}P(),L();try{const t=await h(l,a);p=t.totalHits,u=Math.ceil(p/15),t.hits.length===0?s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):g(t.hits),a<u?b():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){s.error({title:"Error",message:`Sorry, error is ${t.message}`,position:"topRight"})}finally{w()}}async function H(){try{a++,d(),L();const r=await h(l,a);g(r.hits),A(),a<u?b():(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){s.error({title:"Error",message:`Sorry, error is ${r.message}`,position:"topRight"})}finally{w()}}function A(){const t=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
